dependencies {
    implementation project(":mockodile-core")
    implementation 'com.github.tomakehurst:wiremock-jre8-standalone:2.35.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.1'
    testImplementation(testFixtures(project(":mockodile-core")))
}
